config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home", to: 'static_pages#home', as: 'home'
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @flickr = FlickRaw::Flickr.new
    if params[:search]
      unless params[:search][:user_id].blank?
        @photos = flickr.photos.search(user_id: params[:search][:user_id])
      end
    end
  end

  private
    def search_params
      params.require(:search).permit(:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Get Photos from Flickr</h1>

<%= form_for(:search, url: home_path, method: 'get') do |f| %>
  <%= f.label :user_id %>
  <%= f.text_field :user_id, value: params[:search] ? params[:search][:user_id] : "" %>

  <br>

  <%= f.submit "Get Photos" %>
<% end %>

<% if params[:search] %>
  <% @photos.each do |photo| %>
    <div>
      <%= image_tag("https://farm#{photo.farm}.staticflickr.com/#{photo.server}/#{photo.id}_#{photo.secret}.jpg",
                    size: "500",
                    alt: "Image") %>
    </div>
  <% end %>
<% end %>